# Generated by Django 5.0.7 on 2024-07-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupcake',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='cupcake',
            name='updated_at',
        ),
    ]
