# Generated by Django 5.0.7 on 2024-07-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cupcake_valid_alter_cupcake_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='KeyIngredient',
        ),
        migrations.RenameField(
            model_name='cupcake',
            old_name='ingredients',
            new_name='key_ingredients',
        ),
        migrations.RenameField(
            model_name='cupcake',
            old_name='user_id',
            new_name='user',
        ),
    ]
