# Generated by Django 5.0.7 on 2024-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cupcake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupcake',
            name='stupid_article',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
