# Generated by Django 5.0.7 on 2024-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cupcake_stupid_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupcake',
            name='stupid_article',
            field=models.TextField(null=True),
        ),
    ]
